# Generated by Django 5.1.7 on 2025-03-24 00:37

import django.db.models.deletion
import dplapp.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TokensModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pubkey', models.TextField(unique=True, validators=[dplapp.models.TokensModel.validate_public_key])),
                ('is_active', models.BooleanField(default=dplapp.models.ReturnTrue)),
                ('last_activated', models.DateTimeField(blank=True, null=True)),
                ('pin', models.TextField()),
                ('allowed_ips', models.TextField(blank=True, null=True, validators=[dplapp.models.TokensModel.validate_ips])),
            ],
        ),
        migrations.CreateModel(
            name='UsersModel',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('additional_data', models.JSONField(blank=True, null=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AppSettingsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_expiry_period', models.DurationField(blank=True, null=True)),
                ('singleton_enforcer', models.CharField(choices=[('X', 'X')], default='X', editable=False, max_length=1, unique=True)),
                ('enforcing_mode', models.CharField(blank=True, choices=[('of', 'off'), ('on', 'on'), ('gr', 'graceful'), ('dv', 'dev')], max_length=2, null=True)),
                ('activity_period', models.DurationField(blank=True, null=True)),
                ('admin_panel_token', models.UUIDField(blank=True, null=True)),
                ('public_key', models.TextField(blank=True)),
                ('private_key', models.TextField(blank=True)),
                ('ticket_encryption_key', models.BinaryField(blank=True, editable=True)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('activity_period__lt', models.F('ticket_expiry_period'))), name='activity_period__lt__ticket_expiry_period')],
            },
        ),
        migrations.CreateModel(
            name='HistoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('initial_data', models.TextField(blank=True, null=True)),
                ('ip', models.GenericIPAddressField()),
                ('result', models.TextField()),
                ('msg', models.TextField()),
                ('token', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dplapp.tokensmodel')),
            ],
        ),
        migrations.AddField(
            model_name='tokensmodel',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dplapp.usersmodel'),
        ),
    ]
