# Generated by Django 5.1.7 on 2025-03-20 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dplapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersmodel',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
