# Generated by Django 5.1.7 on 2025-03-28 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dplapp', '0002_tokensmodel_can_reset_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersmodel',
            name='additional_data',
            field=models.TextField(blank=True, default=''),
        ),
    ]
