# Generated by Django 5.1.7 on 2025-03-29 06:55

import dplapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dplapp', '0003_alter_usersmodel_additional_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokensmodel',
            name='allowed_ips',
            field=models.TextField(blank=True, default=dplapp.models.ReturnEmptyString, validators=[dplapp.models.TokensModel.validate_ips]),
        ),
    ]
