# Generated by Django 5.1.7 on 2025-03-29 21:31
# edited manually

from django.db import migrations, models
import re
import hashlib

def generate_fingerprint(apps, schema_editor):
    TokensModel = apps.get_model('dplapp', 'TokensModel')
    # print("!!!")
    for token in TokensModel.objects.all():
        if token.pubkey:
            # print("found pubkey")
            cleaned_pubkey = re.sub(r'(\r\n)|\n', '', token.pubkey)
            digest = hashlib.sha256(cleaned_pubkey.encode('utf-8')).digest()
            first_6_bytes = digest[:6]
            fingerprint = ' '.join(f'{byte:02X}' for byte in first_6_bytes)
            # print(f"{fingerprint=}")
            token.fingerprint = fingerprint
            token.save(update_fields=["fingerprint"])
            # print(f"{self.fingerprint=}")

class Migration(migrations.Migration):

    dependencies = [
        ('dplapp', '0004_alter_tokensmodel_allowed_ips'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokensmodel',
            name='fingerprint',
            field=models.CharField(blank=True, editable=False, max_length=17),
        ),
        migrations.RunPython(generate_fingerprint)
    ]
