# Generated by Django 5.1.7 on 2025-03-31 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dplapp', '0005_tokensmodel_fingerprint'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersmodel',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
