# version: '3.8'

services:
  diplomabackend:
    build: .
    container_name: diplomabackend
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - ./db.sqlite3:/app/db.sqlite3
    restart: always
    environment:
      - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE}