name: Deploy to VPS

on:
  push:
    branches:
      - main  # или ваша целевая ветка

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Add VPS to known_hosts
        run: |
            mkdir -p ~/.ssh
            ssh-keyscan -H zaqzxcswsde.ru >> ~/.ssh/known_hosts
      

      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy on VPS
        run: |
          ssh -p 7834 user@zaqzxcswsde.ru "cd /home/user/dplfld/diplomabackend/ && sudo systemctl stop gunicorn.service && git pull && sudo systemctl start gunicorn.service"
