name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Add VPS to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p 7834 -H zaqzxcswsde.ru >> ~/.ssh/known_hosts
      
      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy on VPS via Docker Compose
        run: |
          ssh -p 7834 user@zaqzxcswsde.ru << 'EOF'
            set -e  # Остановить скрипт при любой ошибке

            cd /home/user/dplfld/diplomabackend/
            git pull

            echo "[INFO] Stopping and removing old containers (if exists)..."
            docker compose down || true

            echo "[INFO] Building Docker image via compose..."
            docker compose build

            echo "[INFO] Starting container with compose..."
            docker compose up -d

            echo "[INFO] Waiting for container to start..."
            sleep 5

            echo "[INFO] Checking container status..."
            STATUS=$(docker inspect -f '{{.State.Status}}' diplomabackend)

            if [ "$STATUS" = "running" ]; then
              echo "[SUCCESS] Container is running and initialized."
            else
              echo "[ERROR] Container is NOT running. Status: $STATUS"
              exit 1
            fi
          EOF
